version: "3.7"

networks:
  wp-docker:

volumes:
  db_data: {}

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wp-docker
    container_name: wp-db
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  wordpress:
    build: .
    image: wordpress:latest
    volumes:
      - ./php/php.ini:/usr/local/etc/php/conf.d/wp-php.ini
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/themes:/var/www/html/wp-content/themes
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wp-docker
    depends_on:
      - db
    container_name: wp-app
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
    networks:
      - wp-docker
    depends_on:
      - db
    container_name: phpmyadmin
